apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: accounts.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: Account
    plural: accounts
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - email
            - parentId
            properties:
              externalName:
                type: string
                description: |
                  AWS Account ID to adopt (e.g., 123456789012).
                  When set, Crossplane imports the existing account instead of creating a new one.
              email:
                type: string
                description: AWS account email address. Must be unique across all AWS accounts.
              parentId:
                type: string
                description: AWS Organizations parent ID (root or organizational unit) where the account will be created.
              providerConfigRef:
                type: object
                description: Reference to the management account ProviderConfig used for Organizations operations.
                properties:
                  name:
                    type: string
                    description: Name of the ProviderConfig. Defaults to "default".
                    default: default
                  kind:
                    type: string
                    description: Kind of the ProviderConfig. Defaults to "ProviderConfig".
                    default: ProviderConfig
              managementPolicies:
                type: array
                description: Crossplane management policies propagated to managed resources. Defaults to ["*"].
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"
              policyAttachments:
                type: array
                description: Optional list of Service Control Policy ARNs to attach to the account.
                items:
                  type: string
              tags:
                type: object
                description: "AWS resource tags. Automatically includes {\"hops\": \"true\"}."
                x-kubernetes-preserve-unknown-fields: true
              forProvider:
                type: object
                description: Override any forProvider field on the Account resource. Keys here overwrite template defaults. See provider docs.
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              accountId:
                type: string
                description: AWS account ID of the member account.
              organizationAccountAccessRoleArn:
                type: string
                description: ARN of the OrganizationAccountAccessRole in the member account.
              ready:
                type: boolean
                description: Whether all resources are ready.
